ALTER TABLE marks 
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE students
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE medals
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE marks SET marks.quarterly=IFNULL(marks.quarterly,0),marks.half_yearly=IFNULL(marks.half_yearly,0),marks.annual=IFNULL(marks.annual,0);

ALTER TABLE marks
MODIFY COLUMN quarterly INT NOT NULL,
MODIFY COLUMN half_yearly INT NOT NULL,
MODIFY COLUMN annual INT NOT NULL;